services:
  php:
    container_name: website
    image: website
    build: 
      dockerfile: project/docker/php/Dockerfile
    ports:
      - 8081:80
    volumes:
      - "./project:/var/www/html"
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1960
    ports:
      - 3306:3306
    volumes:
      - "./project/docker/volume/mysql:/var/lib/mysql"
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306

  